replicaCount: 1

namespace: laravel

image:
  repository: 12amit1234/laravel-k8s-app
  tag: "1.1"

config:
  APP_ENV: production

pvc:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce

secret:
  APP_KEY: YW1pdA==
