apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
        - name: laravel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80

          envFrom:
            - configMapRef:
                name: laravel-config
            - secretRef:
                name: laravel-secret

          resources:
{{ toYaml .Values.resources | indent 12 }}

          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 10

          volumeMounts:
            - name: laravel-storage
              mountPath: {{ .Values.pvc.mountPath }}

      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
